### ISSUE TITLE
Error on running starting example

### ISSUE THREAD

**Issue by rishavs** [load1n9/caviar#2]
Hi
I am getting errors on trying to run the given example;
```
import { World, Scene, Rectangle } from 'https://deno.land/x/caviar/mod.ts';


class Game extends Scene {
    public test = new Rectangle(0, 0, 100, 100, "#00ff00");
    public test2 = new Rectangle(0, 0, 100, 100, "#00ff00");
    
    public setup() {
        this.addChild(this.test);
        this.addChild(this.test2);
    }
    public update() {
        this.test.setX(this.test.x + 5);
        this.test2.setX(this.test2.x + 2);
    }

}

const test = new World({
    title: "test",
    width: 800,
    height: 600,
    resizable: true,
}, [Game]);

await test.start();
```
The full trace is;
```
C:\Users\risharan\Documents\Dev\typescript\cav>deno run test.ts
Download https://deno.land/x/caviar/mod.ts
Warning Implicitly using latest version (2.4.1) for https://deno.land/x/caviar/mod.ts
Download https://deno.land/x/caviar@2.4.1/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/Plugin.ts
Download https://deno.land/x/caviar@2.4.1/src/World.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/events/EventManager.ts
Download https://deno.land/x/caviar@2.4.1/src/math/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/renderers/types.ts
Download https://deno.land/x/caviar@2.4.1/src/scenes/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/types.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/Keycodes.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/scenes/Scene.ts
Download https://deno.land/x/caviar@2.4.1/deps.ts
Download https://deno.land/x/caviar@2.4.1/src/renderers/webgl/2d.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Average.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Bernstein.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Between.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Bezier.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Clamp.ts
Download https://deno.land/x/caviar@2.4.1/src/math/Factorial.ts
Download https://deno.land/x/caviar@2.4.1/src/math/FuzzyEqual.ts
Download https://deno.land/x/caviar@2.4.1/src/math/const.ts
Download https://deno.land/x/caviar@2.4.1/src/math/matrices/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/math/vector/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/Entity.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/containers/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/geometry/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/textures/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/Frames.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/HexToRGBA.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/QuadTree.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/atlas/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/renderers/webgl/shader.ts
Download https://deno.land/x/caviar@2.4.1/src/renderers/webgl/types.ts
Download https://deno.land/x/caviar@2.4.1/src/renderers/webgl/util.ts
Download https://deno.land/x/daybreak@v0.0.6/mod.ts
Download https://deno.land/x/gmath@0.1.11/mod.ts
Download https://deno.land/x/caviar@2.4.1/src/math/matrices/TransformMatrix.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/geometry/Rectangle.ts
Download https://deno.land/x/caviar@2.4.1/src/math/vector/Vector.ts
Download https://deno.land/x/caviar@2.4.1/src/math/vector/types.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/Atlas.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/AtlasSprite.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/FrameBuffer.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/Image.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/sprites/Sprite.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/atlas/Atlas.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/atlas/GodotAtlas.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/atlas/PhaserAtlas.ts
Download https://deno.land/x/caviar@2.4.1/src/utils/atlas/PixiAtlas.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/containers/Button.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/containers/Group.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/textures/TextureSprite.ts
Download https://deno.land/x/caviar@2.4.1/src/entities/textures/palettes/mod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/core/mod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/mod.ts
Download https://deno.land/x/gmath@0.1.11/src/angle.ts
Download https://deno.land/x/gmath@0.1.11/src/decomposed.ts
Download https://deno.land/x/gmath@0.1.11/src/matrix2.ts
Download https://deno.land/x/gmath@0.1.11/src/matrix3.ts
Download https://deno.land/x/gmath@0.1.11/src/matrix4.ts
Download https://deno.land/x/gmath@0.1.11/src/projection.ts
Download https://deno.land/x/gmath@0.1.11/src/quaternion.ts
Download https://deno.land/x/gmath@0.1.11/src/vector2.ts
Download https://deno.land/x/gmath@0.1.11/src/vector3.ts
Download https://deno.land/x/gmath@0.1.11/src/vector4.ts
Download https://deno.land/std@0.125.0/path/mod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/util.ts
Download https://deno.land/x/daybreak@v0.0.6/src/core/const.ts
Download https://deno.land/x/daybreak@v0.0.6/src/core/glfw.ts
Download https://deno.land/x/daybreak@v0.0.6/src/core/opengl.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/animation.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/canvas.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/context.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/document.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/element.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/image.ts
Download https://deno.land/x/gmath@0.1.11/wasm/mod.ts
Download https://deno.land/x/gmath@0.1.11/src/util.ts
Download https://deno.land/std@0.125.0/_util/os.ts
Download https://deno.land/std@0.125.0/path/_interface.ts
Download https://deno.land/std@0.125.0/path/common.ts
Download https://deno.land/std@0.125.0/path/glob.ts
Download https://deno.land/std@0.125.0/path/posix.ts
Download https://deno.land/std@0.125.0/path/separator.ts
Download https://deno.land/std@0.125.0/path/win32.ts
Download https://deno.land/x/plug@0.5.1/mod.ts
Download https://deno.land/x/jpegts@1.1/mod.ts
Download https://deno.land/x/pngs@0.1.1/mod.ts
Download https://deno.land/x/gmath@0.1.11/wasm/wasm.js
Download https://deno.land/std@0.125.0/path/_constants.ts
Download https://deno.land/std@0.125.0/path/_util.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/mod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/webgl_object.ts
Download https://deno.land/std@0.125.0/_util/assert.ts
Download https://deno.land/x/plug@0.5.1/plug.ts
Download https://deno.land/x/jpegts@1.1/lib/decoder.ts
Download https://deno.land/x/jpegts@1.1/lib/encoder.ts
Download https://deno.land/x/jpegts@1.1/lib/image.ts
Download https://deno.land/x/jpegts@1.1/lib/pixel.ts
Download https://deno.land/x/pngs@0.1.1/wasm.js
Download https://deno.land/std@0.97.0/encoding/base64.ts
Download https://deno.land/x/lz4@v0.1.2/mod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/angle_instance_arrays.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_blend_minmax.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_color_buffer_float.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_color_buffer_half_float.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_disjoint_timer_query.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_float_blend.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_frag_depth.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_shader_texture_lod.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_srgb.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/ext_texture_filter_anisotropic.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/khr_parallel_shader_compile.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/oes_texture_float_linear.ts
Download https://deno.land/x/daybreak@v0.0.6/src/web/ext/oes_texture_half_float.ts
Download https://deno.land/x/plug@0.5.1/deps.ts
Download https://deno.land/x/lz4@v0.1.2/wasm.js
Download https://deno.land/std@0.122.0/fmt/colors.ts
Download https://deno.land/std@0.122.0/path/mod.ts
Download https://deno.land/x/cache@0.2.13/mod.ts
Download https://deno.land/x/cache@0.2.13/cache.ts
Download https://deno.land/std@0.122.0/_util/os.ts
Download https://deno.land/std@0.122.0/path/_interface.ts
Download https://deno.land/std@0.122.0/path/common.ts
Download https://deno.land/std@0.122.0/path/glob.ts
Download https://deno.land/std@0.122.0/path/posix.ts
Download https://deno.land/std@0.122.0/path/separator.ts
Download https://deno.land/std@0.122.0/path/win32.ts
Download https://deno.land/x/cache@0.2.13/deps.ts
Download https://deno.land/x/cache@0.2.13/directories.ts
Download https://deno.land/x/cache@0.2.13/file.ts
Download https://deno.land/x/cache@0.2.13/helpers.ts
Download https://deno.land/std@0.122.0/path/_constants.ts
Download https://deno.land/std@0.122.0/path/_util.ts
Download https://deno.land/std@0.122.0/_util/assert.ts
Download https://deno.land/std@0.97.0/fs/ensure_dir.ts
Download https://deno.land/std@0.97.0/fs/exists.ts
Download https://deno.land/std@0.97.0/hash/mod.ts
Download https://deno.land/std@0.97.0/path/mod.ts
Download https://deno.land/x/cache@0.2.13/file_fetcher.ts
Download https://deno.land/std@0.97.0/fs/_util.ts
Download https://deno.land/std@0.97.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.97.0/hash/hasher.ts
Download https://deno.land/std@0.97.0/_util/os.ts
Download https://deno.land/std@0.97.0/path/_interface.ts
Download https://deno.land/std@0.97.0/path/common.ts
Download https://deno.land/std@0.97.0/path/glob.ts
Download https://deno.land/std@0.97.0/path/posix.ts
Download https://deno.land/std@0.97.0/path/separator.ts
Download https://deno.land/std@0.97.0/path/win32.ts
Download https://deno.land/std@0.97.0/encoding/hex.ts
Download https://deno.land/std@0.97.0/hash/_wasm/wasm.js
Download https://deno.land/std@0.97.0/path/_constants.ts
Download https://deno.land/std@0.97.0/path/_util.ts
Download https://deno.land/std@0.97.0/_util/assert.ts
Check file:///C:/Users/risharan/Documents/Dev/typescript/cav/test.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'NativeType'.
export type MapType<T extends Deno.NativeType> = T extends "u8" ? number
                                   ~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:1:36

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
  : T extends "pointer" ? Deno.UnsafePointer
                               ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:11:32

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'NativeType'.
export type MapParamType<T extends Deno.NativeType> = T extends "pointer" ? (
                                        ~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:15:41

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
  | Deno.UnsafePointer
         ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:16:10

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'NativeType'.
export type MapParameters<T extends Deno.NativeType[]> = [
                                         ~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:32:42

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'NativeType'.
    [K in keyof T]: T[K] extends Deno.NativeType ? MapParamType<T[K]> : unknown;
                                      ~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:34:39

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ForeignFunction'.
export type MapFunction<T extends Deno.ForeignFunction> = (
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:38:40

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ForeignFunction'.
export type MapFFI<T extends Record<string, Deno.ForeignFunction>> = {
                                                 ~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/util.ts:43:50

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
export function init(GetProcAddress: (name: string) => Deno.UnsafePointer) {
                                                            ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/core/opengl.ts:1277:61

TS2339 [ERROR]: Property 'UnsafeFnPointer' does not exist on type 'typeof Deno'.
    const fnptr = new Deno.UnsafeFnPointer(
                           ~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/core/opengl.ts:1287:28

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ForeignFunction'.
      (symbols as Record<string, Deno.ForeignFunction>)[name],
                                      ~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/core/opengl.ts:1289:39

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ForeignFunction'.
export async function prepare<S extends Record<string, Deno.ForeignFunction>>(
                                                            ~~~~~~~~~~~~~~~
    at https://deno.land/x/plug@0.5.1/plug.ts:101:61

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'DynamicLibrary'.
): Promise<Deno.DynamicLibrary<S>> {
                ~~~~~~~~~~~~~~
    at https://deno.land/x/plug@0.5.1/plug.ts:104:17

TS2551 [ERROR]: Property 'dlopen' does not exist on type 'typeof Deno'. 'Deno.dlopen' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'open'?
  return Deno.dlopen(file, symbols);
              ~~~~~~
    at https://deno.land/x/plug@0.5.1/plug.ts:106:15

    'open' is declared here.
      export function open(
                      ~~~~
        at asset:///lib.deno.ns.d.ts:850:19

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ForeignFunction'.
    Deno.ForeignFunction
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/core/glfw.ts:616:10

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
    lib.symbols.glfwGetProcAddress(cstr(name)) as Deno.UnsafePointer
                                                       ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/core/glfw.ts:623:56

TS2339 [ERROR]: Property 'UnsafePointerView' does not exist on type 'typeof Deno'.
          const str = new Deno.UnsafePointerView(ptr).getCString();
                               ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:931:32

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
    sourcePtr[0] = Deno.UnsafePointer.of(sourceEncoded).value;
                        ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:2029:25

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
      new Deno.UnsafePointer(BigInt(offset)),
               ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:2583:16

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
      new Deno.UnsafePointer(BigInt(offset)),
               ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:2611:16

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
        ? new Deno.UnsafePointer(BigInt(pixels))
                   ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:2644:20

TS2339 [ERROR]: Property 'UnsafePointerView' does not exist on type 'typeof Deno'.
    const view = new Deno.UnsafePointerView(mapped);
                          ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:3022:27

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
      ptrs[i] = Deno.UnsafePointer.of(varyingCstrs[i]).value;
                     ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:3492:22

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
      pointers[i] = Deno.UnsafePointer.of(e).value;
                         ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/context.ts:3549:26

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
  handle: Deno.UnsafePointer;
               ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/canvas.ts:16:16

TS2339 [ERROR]: Property 'UnsafePointerView' does not exist on type 'typeof Deno'.
          new Deno.UnsafePointerView(new Deno.UnsafePointer(errptr[0]))
                   ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/canvas.ts:64:20

TS2339 [ERROR]: Property 'UnsafePointer' does not exist on type 'typeof Deno'.
          new Deno.UnsafePointerView(new Deno.UnsafePointer(errptr[0]))
                                              ~~~~~~~~~~~~~
    at https://deno.land/x/daybreak@v0.0.6/src/web/canvas.ts:64:47

TS2339 [ERROR]: Property 'setX' does not exist on type 'Rectangle'.        this.test.setX(this.test.x + 5);
                  ~~~~
    at file:///C:/Users/risharan/Documents/Dev/typescript/cav/test.ts:13:19

TS2339 [ERROR]: Property 'setX' does not exist on type 'Rectangle'.
        this.test2.setX(this.test2.x + 2);
                   ~~~~
    at file:///C:/Users/risharan/Documents/Dev/typescript/cav/test.ts:14:20

Found 30 errors.
```

**Comment by load1n9** [comment]
thank you ill fix this
