### ISSUE TITLE
GlfwError: 65542 WGL

### ISSUE THREAD

**Issue by jake22lindsay** [load1n9/caviar#5]
I downloaded and ran the two moving rectangles starter program, but I seem to missing a driver of some sort. The full error is below. Has a solution been found for this problem?

Full error:
GlfwError: 65542 WGL: OpenGL ES requested but WGL_ARB_create_context_es2_profile is unavailable
error: Uncaught (in promise) Error: Failed to create window
      throw new Error("Failed to create window");
            ^
    at new WindowGlfw (https://raw.githubusercontent.com/deno-windowing/dwm/main/src/platform/glfw/window.ts:563:13)
    at createWindow (https://raw.githubusercontent.com/deno-windowing/dwm/main/src/platform/mod.ts:29:10)
    at new WebGLCanvas (https://raw.githubusercontent.com/deno-windowing/gluten/main/src/webgl/canvas.ts:18:19)
    at new World (https://deno.land/x/caviar@2.6.0/src/World.ts:22:5)
    at file:///C:/Users/jakel/OneDrive/UNH/sem7/IT%20505/repos/finalproject/app/app.ts:16:14

**Comment by load1n9** [comment]
maybe try using an older version of caviar while i fix this

**Comment by jake22lindsay** [comment]
Update:
Versions 2.4.0 and 2.5.0 lead to a different issue. Any previous versions invalidates the code provided in the two rectangle example. 

error: Uncaught (in promise) TypeError: Invalid FFI pointer type, expected null, integer or BigInt
    this.handle = glfw.createWindow(
                       ^
    at Object.eval [as createWindow] (eval at DynamicLibrary (deno:ext/ffi/00_ffi.js:360:34), <anonymous>:4:13)
    at new Canvas (https://deno.land/x/daybreak@v0.0.6/src/web/canvas.ts:52:24)
    at new World (https://deno.land/x/caviar@2.4.0/src/World.ts:18:5)
    at file:///C:/Users/jakel/OneDrive/UNH/sem7/IT%20505/repos/finalproject/tests/caviar.ts:16:14

**Comment by load1n9** [comment]
is this still broken?

**Comment by SunOfHomeBoy** [comment]
> is this still broken?

yes, please repair as soon as possible

**Comment by SunOfHomeBoy** [comment]
Besides, the link in Readme opens as 404
![image](https://github.com/load1n9/caviar/assets/30047595/1ef0cb00-25f5-4056-86c7-250f69ebd01a)
![image](https://github.com/load1n9/caviar/assets/30047595/c0acfd93-ecc1-491e-b760-766a50ad2c5d)
