### ISSUE TITLE
Uncaught TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by AngelGamer29JA** [load1n9/caviar#8]
error: Uncaught TypeError: Cannot convert object to primitive value
        new BigUint64Array([BigInt(Deno.UnsafePointer.of(buf))]).buffer,
                            ^
    at BigInt (<anonymous>)
    at WebGLRenderingContext.shaderSource (https://deno.land/x/gluten@0.1.4/src/webgl/renderingContext.ts:737:29)
    at loadShader (https://deno.land/x/caviar@2.6.2/src/renderers/webgl/util.ts:41:8)
    at initShaderProgram (https://deno.land/x/caviar@2.6.2/src/renderers/webgl/util.ts:15:24)
    at new WebGLRenderer2D (https://deno.land/x/caviar@2.6.2/src/renderers/webgl/2d.ts:40:21)
    at new World (https://deno.land/x/caviar@2.6.2/src/World.ts:29:21)
    at file:///C:/Users/popit/workspace/deno/kekotest/main.ts:8:14

**Comment by load1n9** [comment]
Will look into seems like a gluten issue

**Comment by load1n9** [comment]
can you send me the code used

**Comment by AngelGamer29JA** [comment]
import { Rectangle, Scene, World } from "https://deno.land/x/caviar/mod.ts";

class Game extends Scene {
  test = new Rectangle(0, 0, 100, 100, "#00ff00");
  test2 = new Rectangle(0, 0, 100, 100, "#00ff00");

  setup() {
    this.addChild([this.test, this.test2]);
  }
  update() {
    this.test.x += 5;
    this.test2.x += 2;
  }
}

const world = new World({
  title: "",
  width: 800,
  height: 600,
  resizable: true,
}, [Game]);

await world.start();
